# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.define :microA do |microA|
    microA.vm.box = "centos1706_v0.3.0"
    microA.vm.network :private_network, ip: "192.168.33.13"
  #  microA.vm.network "public_network", bridge: "eno1", ip:"192.168.131.43", netmask: "255.255.255.0"
    microA.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "microA" ]
	microA.vm.provision "shell", path: "install.sh"
    end
  end
end
